parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  node: true
  es6: true
  mocha: true
parser: babel-eslint
extends:
  - standard
plugins:
  - import
rules:
  no-console: warn
  comma-dangle: off

  import/named: error
  import/namespace: error
