require('dotenv').config()
const express = require('express')
const cors = require('cors')
const helmet = require('helmet')
const morgan = require('morgan')
const Boom = require('boom')

const server = express()
const app = require('./app')
const errorHandler = require('./app/error/errorhandler')

server.use(cors())
server.use(helmet())
server.use(morgan('dev'))
server.use('/v1', app)
server.all('*', (req, res, next) => next(Boom.unauthorized()))
server.use(errorHandler)

server.listen(3000)
console.log('Server start at: http://localhost:3000')
